# NumPy


In [ ]:
import numpy as np
# 创建数组
a = np.array([1, 2, 3,4,5,6,7])

# 创建二维数组  
b = np.array([[1, 2], [3, 4]])

# 创建三维数组  。。。

# 创建全0数组
c = np.zeros((2, 3))

# 创建全1数组
d = np.ones((2, 3))

# 创建指定值数组
e = np.full((2, 3), 8) 

# 创建单位矩阵
f = np.eye(3)

# 创建随机数组
g = np.random.random((2, 3))

# 创建等差数组  
i = np.linspace(1, 10, 5)

print(a)
print(b)
print(c)
print(d)
print(e)
print(f)
print(g)
print(i)


[1 2 3]
[[1 2]
 [3 4]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[8 8 8]
 [8 8 8]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0.64021462 0.3858379  0.84751393]
 [0.57621175 0.13422636 0.40949311]]
[ 1.    3.25  5.5   7.75 10.  ]


In [2]:
#数组索引
print(a[0])
print(a[1:3])
print(b[0][0])
print(b[0, 0])#等价于上面的 
print(b[0, :])#取第一行
print(b[:, 0])#取第一列
print(b[0, 0:2])#取第一行的前两个元素




1
[2 3]
1
1
[1 2]
[1 3]
[1 2]


In [7]:
#数组拼接和分割
#np.concatenate()：沿着指定轴拼接数组。
k=np.array([1,2,3,4,5,65,67,0,7])
l=np.array([7,8,9,10,11,12,13,14,15])
m=np.concatenate([k,l])#横向拼接
print(m)
#np.vstack()：沿着垂直方向拼接数组。
n=np.vstack([k,l])
print(n)
#np.split()：沿着指定轴分割数组。
o=np.split(n,2)#将n分割成两个数组   
print(o)


[ 1  2  3  4  5 65 67  0  7  7  8  9 10 11 12 13 14 15]
[[ 1  2  3  4  5 65 67  0  7]
 [ 7  8  9 10 11 12 13 14 15]]
[array([[ 1,  2,  3,  4,  5, 65, 67,  0,  7]]), array([[ 7,  8,  9, 10, 11, 12, 13, 14, 15]])]


In [ ]:
#数组运算
#数组与标量运算
print(a+1)
print(a-1)
print(a*2)
print(a/2)
#数组与数组运算
print(a+a)
print(a-a)
print(a*a)
print(a/a)
#数组与数组之间的运算
print(a+b)
print(a-b)
print(a*b)
print(a/b)
#数组的矩阵运算
print(np.dot(a,b))#矩阵乘法
print(np.transpose(b))#矩阵转置
print(np.linalg.inv(b))#矩阵求逆
print(np.linalg.det(b))#矩阵求行列式
print(np.linalg.eig(b))#矩阵求特征值和特征向量
print(np.linalg.solve(b,a))#求解线性方程组
#广播支持不同形状数组之间的计算。
p=np.array([[1,2,3],[4,5,6],[7,8,9]])
q=np.array([1,0,1])
print(p+q)


#统计函数
#np.sum()：求和。
print(np.sum(a))
print(np.sum(b))
print(np.sum(b,axis=0))#按列求和
print(np.sum(b,axis=1))#按行求和
#np.mean()：求平均值。
print(np.mean(a))
print(np.mean(b))
print(np.mean(b,axis=0))#按列求平均值
print(np.mean(b,axis=1))#按行求平均值
#np.std()：求标准差。
print(np.std(a))
print(np.std(b))
print(np.std(b,axis=0))#按列求标准差

#np.min()：求最小值。
print(np.min(a))
print(np.min(b))
print(np.min(b,axis=0))#按列求最小值
print(np.min(b,axis=1))#按行求最小值
#np.max()：求最大值。
# 。。。

#np.argmin()：求最小值的索引。
print(np.argmin(a))
print(np.argmin(b))
print(np.argmin(b,axis=0))#按列求最小值的索引
print(np.argmin(b,axis=1))#按行求最小值的索引







In [ ]:
#数组的生成·
#np.arange()：生成等差数组。
print(np.arange(10))
print(np.arange(1,10,2))
#np.linspace()：生成等差数组。
print(np.linspace(1,10,5))
#np.logspace()：生成等比数组。
print(np.logspace(0,2,3))
#np.zeros()：生成全0数组。
print(np.zeros(5))
print(np.zeros((2,3)))
#生成均匀分布的随机数。
print(np.random.rand(5))
#生成正态分布的随机数。
print(np.random.randn(5))
#生成随机整数。
print(np.random.randint(1,10,5))